### ISSUE TITLE
Fix high data usage

### ISSUE THREAD

**Issue by patil215** [project-manatee/manatee-android#13]
Currently the app uses tons of data when fetching grades in the background.

Fixes/optimizations:
-Reduce polling interval to an hour
-Only poll in background if on Wi-Fi, or reduce polling interval if on 3G
-Only poll assignments for the latest cycle
-Add a manual refresh button to assignments
-When opening cycle/assignments page from app, check how long it's been since the cycle was last loaded and load new assignments if it's been a while
-Check for hanging or loops

**Comment by GladiusMaximus** [comment]
Allow user to set polling time.

On Friday, January 9, 2015, Neil Patil <notifications@github.com> wrote:

> Currently the app uses tons of data when fetching grades in the background.
>
> Fixes/optimizations:
> -Reduce polling interval to an hour
> -Only poll in background if on Wi-Fi, or reduce polling interval if on 3G
> -Only poll assignments for the latest cycle
> -Add a manual refresh button to assignments
> -When opening cycle/assignments page from app, check how long it's been
> since the cycle was last loaded and load new assignments if it's been a
> while
> -Check for hanging or loops
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/project-manatee/manatee-android/issues/13>.
>


-- 
Sam G
