### ISSUE TITLE
First time pointers

### ISSUE THREAD

**Issue by patil215** [project-manatee/manatee-android#5]
Add some information to be shown the first time opening the app. This can be done with ShowCaseViewLib and includes:
-Tap on grades card to view assignments
-GPA disclaimer (not 100% accurate)
-Tap on GPA to change weighted/excluded classes
-How the graphs work (track grade progress as each day goes on, check back in a few weeks)
-Disclaimer on graphs
-Grade change notifications

**Comment by Oksisane** [comment]
6f8d8861c0bbccfd2eedf5a750f428a61618de00 finishes implementation of showcaseview, all that is left to be added are the disclaimers/tweaking the text by @patil215
